<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Index.aspx.cs" Inherits="SignalRChat.Index" %>
<% if (Session["UserId"] == null) { Response.Redirect("~/Login.aspx");}
%>

<!DOCTYPE html>
<html>
<head>
    <title>SignalR Simple Chat</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    
</head>
<body>
    <div class="container">

        <div  style="margin:40px">
             <input type="text" id="message" onkeydown="if (event.keyCode == 13) {sendMessage(); return false; }"  />
            <button type="button" id="sendmessage" class="btn btn-primary">Enviar</button>

        </div>
       

        <input type="hidden" id="displayname" />
        
        <ul id="discussion" class="list-group">
         
        </ul>
    </div>
    <!--Referencias de Script. -->
    <!--Referencias de jQuery library. -->
    <script src="Scripts/jquery-3.4.1.min.js"></script>
    <!--Referencias de SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Referencias de autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
        var chat = null;
        var sendMessage = function () {
            // Llama el método "send" al hub.
            chat.server.send($('#displayname').val(), $('#message').val());
            // Limpia la caja de texto y resetea el "focus" para el siguiente comentario.
            $('#message').val('').focus();
        }
        $(function () {
            // Declara una referencia proxy al hub.
            chat = $.connection.chatHub;
           

            // Crea una función que el hub puede llamar para transmitir mensajes.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode muestra mensaje y nombre.
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Agregar mensajes a la página.A
                $('#discussion').prepend('<li class="list-group-item"><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };
            // Obtener usuario y agregar su nombre antes del mensaje.
            $('#displayname').val('<%=Session["UserId"]%>');
            // Set initial focus to message input box.
            $('#message').focus();
            // Iniciar la conección.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(sendMessage);
            });
        });

       
    </script>
</body>
</html>
